language: java
jdk:
  - openjdk11

branches:
  only:
    - main
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/idol-collector.zip


# https://docs.travis-ci.com/user/deployment/s3/ 공식 docs
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: idol-collector-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private  # zip 파일 접근 private
    local_dir: deploy  # befroe_deploy에서 생성한 폴더
    #wait-until-deployed: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: idol-collector-build
    key: idol-collector.zip
    bundle_type: zip
    application: idol-collector
    deployment_group: idol-collector-group
    region: ap-northeast-2
    on:
      all_branches: true




# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - totw5701@naver.com