export const ADD_LIKE = 'ADD_LIKE'
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const ADD_VIEW = 'ADD_VIEW'
export const GET_HOME = 'GET_HOME'
export const GET_MEMBER = 'GET_MEMBER'
export const USER_CARD = 'USER_CARD'
export const USER_SCRAP = 'USER_SCRAP'